cmake_minimum_required(VERSION 4.3)

SET(CMAKE_CXX_STANDARD 23)
SET(CMAKE_COLOR_DIAGNOSTICS ON)


PROJECT(KrakenAPIWrapper VERSION 0.1
        DESCRIPTION "Kraken API Wrapper"
        LANGUAGES C CXX)

FIND_PROGRAM(CCACHE_EXECUTABLE ccache)
IF (CCACHE_EXECUTABLE)
    MESSAGE(STATUS "Enabling ccache")
    SET(CMAKE_C_COMPILER_LAUNCHER "${CCACHE_EXECUTABLE}" CACHE STRING "C compiler launcher")
    SET(CMAKE_CXX_COMPILER_LAUNCHER "${CCACHE_EXECUTABLE}" CACHE STRING "C++ compiler launcher")
ELSE ()
    MESSAGE(STATUS "ccache was not found")
ENDIF ()


FIND_PACKAGE(OpenSSL REQUIRED)
FIND_PACKAGE(simdjson REQUIRED)
FIND_PACKAGE(cpr REQUIRED)
FIND_PACKAGE(libwebsockets REQUIRED)


INCLUDE(kraken-warnings.cmake)

ADD_LIBRARY(kraken STATIC main.cpp
        include/krakendefs.hpp)

TARGET_COMPILE_DEFINITIONS(kraken PRIVATE USE_EXPORT_LIBRARY)
